server:
  port: 8080
  servlet:
    context-path: /api_hub
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    url: jdbc:mysql://api-hub.wayne.com:3306/api_hub?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: api_hub
    password: api_hub@2021
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      initial-size: 1
      min-idle: 1
      max-active: 20
      max-wait: 60000
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      max-evictable-idle-time-millis: 900000
      validation-query: SELECT 1
      test-on-borrow: true
      test-while-idle: true
logging:
  config: classpath:log4j2.xml
  level:
    com.wayne.apihub: debug
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mappers/*.xml
springdoc:
  api-docs:
    path: /openapi
  packages-to-scan:
    - com.wayne.apihub.modules
    - com.wayne.apihub.model
  paths-to-match: /v1/**
