server:
  port: 8080
  servlet:
    context-path: /api_hub
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    url: jdbc:mysql://api-hub.wayne.com:3306/api_hub?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: api_hub
    password: api_hub@2021
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 1
      maximum-pool-size: 20
      connection-timeout: 60000
      idle-timeout: 300000
      max-lifetime: 900000
      keepalive-time: 60000
      connection-test-query: SELECT 1
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 20
        prepStmtCacheSqlLimit: 2048
logging:
  config: classpath:logback-spring.xml
  level:
    root: info
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mappers/*.xml
springdoc:
  api-docs:
    path: /openapi
  packages-to-scan:
    - com.wayne.apihub.modules
    - com.wayne.apihub.model
  paths-to-match: /v1/**
